# robot defintion file for MH5 humanoid robot
#
MH5:
  buses:
    ttySC1:
      class: SharedDynamixelBus
      port: /dev/ttySC1
      baudrate: 1000000
      rs485: True
      protocol: 2.0

    ttySC0:
      class: SharedDynamixelBus
      port: /dev/ttySC0
      baudrate: 1000000
      rs485: True
      protocol: 2.0


  inits:
    common:
      torque_enable: 0
      return_delay_time: 0
      drive_mode: 0
      operating_mode: 3
      moving_threshold: 10
      temperature_limit: 75
      max_voltage_limit: 14.0
      velocity_limit: 1023
      max_position_limit: 4095
      min_position_limit: 0
  
  devices:
    d11:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 11
      model: 2XL430
      inits: [common]

    d12:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 12
      model: 2XL430
      inits: [common]

    d13:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 13
      model: XL430
      inits: [common]

    d14:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 14
      model: 2XL430
      inits: [common]

    d15:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 15
      model: 2XL430
      inits: [common]
    
    d16:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 16
      model: XL430
      inits: [common]

    d21:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 21
      model: 2XL430
      inits: [common]

    d22:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 22
      model: 2XL430
      inits: [common]

    d23:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 23
      model: XL430
      inits: [common]

    d24:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 24
      model: 2XL430
      inits: [common]

    d25:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 25
      model: 2XL430
      inits: [common]

    d26:
      class: DynamixelDevice
      bus: ttySC1
      dev_id: 26
      model: XL430
      inits: [common]

    d31:
      class: DynamixelDevice
      bus: ttySC0
      dev_id: 31
      model: XL430
      inits: [common]

    d32:
      class: DynamixelDevice
      bus: ttySC0
      dev_id: 32
      model: 2XL430
      inits: [common]

    d33:
      class: DynamixelDevice
      bus: ttySC0
      dev_id: 33
      model: 2XL430
      inits: [common]

    d34:
      class: DynamixelDevice
      bus: ttySC0
      dev_id: 34
      model: XL430
      inits: [common]

    d41:
      class: DynamixelDevice
      bus: ttySC0
      dev_id: 41
      model: XL430
      inits: [common]

    d42:
      class: DynamixelDevice
      bus: ttySC0
      dev_id: 42
      model: 2XL430
      inits: [common]

    d43:
      class: DynamixelDevice
      bus: ttySC0
      dev_id: 43
      model: 2XL430
      inits: [common]

    d44:
      class: DynamixelDevice
      bus: ttySC0
      dev_id: 44
      model: XL430
      inits: [common]

    d51:
      class: DynamixelDevice
      bus: ttySC0
      dev_id: 51
      model: 2XL430
      inits: [common]

    d52:
      class: DynamixelDevice
      bus: ttySC0
      dev_id: 52
      model: 2XL430
      inits: [common]

  joints:
    l_ankle_r:
      class: JointPV
      device: d11
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable

    l_ankle_p:
      class: JointPV
      device: d12
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    l_knee_p:
      class: JointPV
      device: d13
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable

    l_hip_p:
      class: JointPV
      device: d14
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    l_hip_r:
      class: JointPV
      device: d15
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable

    l_hip_y:
      class: JointPV
      device: d16
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    l_elbow_p:
      class: JointPV
      device: d31
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    l_elbow_y:
      class: JointPV
      device: d32
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    l_shoulder_r:
      class: JointPV
      device: d33
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    l_shoulder_p:
      class: JointPV
      device: d34
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    r_ankle_r:
      class: JointPV
      device: d21
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    r_ankle_p:
      class: JointPV
      device: d22
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    r_knee_p:
      class: JointPV
      device: d23
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable

    r_hip_p:
      class: JointPV
      device: d24
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    r_hip_r:
      class: JointPV
      device: d25
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable

    r_hip_y:
      class: JointPV
      device: d26
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable

    r_elbow_p:
      class: JointPV
      device: d41
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    r_elbow_y:
      class: JointPV
      device: d42
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable

    r_shoulder_r:
      class: JointPV
      device: d43
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable

    r_shoulder_p:
      class: JointPV
      device: d44
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable

    head_p:
      class: JointPV
      device: d51
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable
      inverse: True

    head_y:
      class: JointPV
      device: d52
      pos_read: present_position_deg
      pos_write: goal_position_deg
      vel_read: present_velocity_dps
      vel_write: goal_velocity_dps
      activate: torque_enable

  groups:

    d_left_leg:
      devices: [d11, d12, d13, d14, d15, d16]

    d_right_leg:
      devices: [d21, d22, d23, d24, d25, d26]

    d_left_arm:
      devices: [d31, d32, d33, d34]
    
    d_right_arm:
      devices: [d41, d42, d43, d44]

    d_head:
      devices: [d51, d52]

    d_legs:
      groups: [d_left_leg, d_right_leg]

    d_lower_body:
      groups: [d_legs]

    d_arms:
      groups: [d_left_arm, d_right_arm]

    d_upper_body:
      groups: [d_arms, d_head]

    all_servos:
      groups: [d_upper_body, d_lower_body]

  syncs:
    present_upper:
      class: DynamixelSyncReadLoop
      group: d_upper_body
      registers: [present_load, present_velocity, present_position]
      frequency: 100.0
      auto: False

    present_lower:
      class: DynamixelSyncReadLoop
      group: d_lower_body
      registers: [present_load, present_velocity, present_position]
      frequency: 100.0
      auto: False
